module Agent
  module Scopes
    module AutoGenerated
      extend ActiveSupport::Concern
      include Agent::Scopes::AutoScope

      class_methods do
        def inherited(child)
          super(child)

          # This TracePoint is used to include the scopes after everything else
          # (when the final `end` of the enclosing class is reached. The included
          # concerns only add scopes if they are *not* already defined in the
          # class.
          TracePoint.trace(:end) do |t|
            if child == t.self
              child.include(Agent::Scopes::Lib::Boolean)
              child.include(Agent::Scopes::Lib::TimeRelated)
              child.include(Agent::Scopes::Lib::LikeAndIs)
              child.include(Agent::Scopes::Lib::WithAndWithout)
              t.disable
            end
          end
        end
      end
    end
  end
end
