database:
  service: Postgresql

database_public:
  service: Postgresql
  public: true # the generated URLs will not expire

cloudflare:
  service: S3
  endpoint: https://<%= Agent::Setting.cloudflare_account_id %>.r2.cloudflarestorage.com
  access_key_id: <%= Agent::Setting.cloudflare_access_key_id %>
  secret_access_key: <%= Agent::Setting.cloudflare_secret_access_key %>
  region: auto
  bucket: <%= Agent::Setting.cloudflare_bucket %>
