module Agent
  class ApplicationRecord < ActiveRecord::Base
    primary_abstract_class

    require_relative "concerns/rollup_cache"
    require_relative "concerns/scopes/auto_scope"
    require_relative "concerns/scopes/lib/boolean"
    require_relative "concerns/scopes/lib/like_and_is"
    require_relative "concerns/scopes/lib/with_and_without"
    require_relative "concerns/scopes/lib/time_related"
    require_relative "concerns/scopes/auto_generated"
    include Agent::RollupCache
    include Agent::Scopes::AutoGenerated
  end
end
