class CreateClients < ActiveRecord::Migration[8.0]
  def change
    create_table "clients" do |t|
      t.bigint "person_id", null: false
      t.string "token", null: false,
               comment: "Auto-generated by rails and saved in browser cookie"
      t.string "platform", comment: "e.g. ios android web"
      t.string "user_agent"
      t.string "ip_address"
      t.timestamps
    end

    add_index "clients", ["person_id"], name: "index_clients_on_person_id"
    add_index "clients", ["token"],     name: "index_clients_on_token", unique: true

    add_foreign_key "clients", "people"
  end
end
